theme: jekyll-theme-cayman
url: https://georgeganea.com
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
title: George Ganea
description: A Java dev lost in Pharo land
